import {
  boolean,
  date,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

/** Task lifecycle — overdue is derived in queries, not stored. */
export const taskStatusEnum = pgEnum("task_status", [
  "pending",
  "in_progress",
  "completed",
]);

/** Alert kinds generated by the app (6pm reminder, overdue, congrats). */
export const alertTypeEnum = pgEnum("alert_type", [
  "completion_congrats",
  "reminder_6pm",
  "overdue",
]);

/**
 * Daily tasks. memberId matches a registered user's roster id.
 * Multiple rows per member per due_date are allowed.
 */
export const tasks = pgTable(
  "tasks",
  {
    id: text("id").primaryKey(),
    memberId: text("member_id").notNull(),
    title: text("title").notNull(),
    notes: text("notes"),
    dueDate: date("due_date").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    startTime: timestamp("start_time", { withTimezone: true, mode: "date" }),
    endTime: timestamp("end_time", { withTimezone: true, mode: "date" }),
    durationMinutes: integer("duration_minutes"),
    status: taskStatusEnum("status").notNull().default("pending"),
    /** User who created the task (session at POST time). */
    assignedByUserId: text("assigned_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
  },
  (table) => [
    index("tasks_member_due_date_idx").on(table.memberId, table.dueDate),
    index("tasks_member_status_idx").on(table.memberId, table.status),
    index("tasks_due_date_status_idx").on(table.dueDate, table.status),
    index("tasks_member_completed_at_idx").on(
      table.memberId,
      table.completedAt
    ),
  ]
);

/**
 * In-app alerts for a team member. taskId is optional (e.g. reminder_6pm).
 */
export const alerts = pgTable(
  "alerts",
  {
    id: text("id").primaryKey(),
    type: alertTypeEnum("type").notNull(),
    memberId: text("member_id").notNull(),
    taskId: text("task_id").references(() => tasks.id, {
      onDelete: "set null",
    }),
    message: text("message").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    read: boolean("read").notNull().default(false),
    /** Prevents duplicate alerts for the same event/day. */
    dedupeKey: text("dedupe_key").unique(),
  },
  (table) => [
    index("alerts_member_read_created_idx").on(
      table.memberId,
      table.read,
      table.createdAt
    ),
    index("alerts_task_id_idx").on(table.taskId),
    index("alerts_type_created_idx").on(table.type, table.createdAt),
  ]
);

/**
 * Registered users. memberId is the roster id used by tasks and alerts.
 */
export const users = pgTable("users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  memberId: text("member_id"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
});

/** Hashed one-time codes for email sign-in and registration. */
export const otpCodes = pgTable(
  "otp_codes",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    codeHash: text("code_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
    used: boolean("used").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("otp_codes_email_created_idx").on(table.email, table.createdAt)]
);

/** httpOnly cookie sessions — raw token never stored, only its hash. */
export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    tokenHash: text("token_hash").notNull().unique(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("sessions_user_id_idx").on(table.userId)]
);
